# Full NixOS System Configuration
# This configuration provides a complete NixOS setup with all features
# from the original dotfiles repository

{ config, pkgs, lib, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Modular configurations
    ./modules/boot.nix
    ./modules/networking.nix
    ./modules/desktop.nix
    ./modules/services.nix
    ./modules/users.nix
  ];

  # Nix settings
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;

      # Trusted users for Nix daemon
      trusted-users = [ "root" "@wheel" ];

      # Substituters
      substituters = [
        "https://cache.nixos.org/"
        "https://nix-community.cachix.org"
      ];

      trusted-public-keys = [
        "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];
    };

    # Automatic garbage collection
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };

    # Automatic Nix store optimization
    optimise = {
      automatic = true;
      dates = [ "weekly" ];
    };
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # System-wide environment variables
  environment.variables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    BROWSER = "google-chrome-stable";
  };

  # System packages (minimal set - most installed via Home Manager)
  environment.systemPackages = with pkgs; [
    # Core utilities
    vim
    neovim
    wget
    curl
    git
    htop

    # Home Manager
    home-manager

    # Essential tools
    pciutils
    usbutils
    lsof
    strace

    # Network tools
    nmap
    netcat
    socat
  ];

  # Enable zsh system-wide
  programs.zsh.enable = true;

  # Enable dconf (needed for GTK apps)
  programs.dconf.enable = true;

  # Security and hardening
  security = {
    rtkit.enable = true;  # RealtimeKit for audio
    polkit.enable = true;

    # Sudo configuration
    sudo = {
      enable = true;
      wheelNeedsPassword = true;
    };
  };

  # System state version
  # WARNING: Don't change this after installation
  system.stateVersion = "24.05";
}
