# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt
[package]
disabled = true

# Customize the git branch display
[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = "…/"

# Customize the directory display
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"

# Show command execution time
[cmd_duration]
min_time = 500
format = "underwent [$duration]($style) "

# Customize the line break
[line_break]
disabled = false

# Customize the hostname display
[hostname]
ssh_only = true
format = "[$hostname](bold red) "
disabled = false

# Customize the username display
[username]
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) "

# Customize the time display
[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
time_range = "-" 